[project]
name = "iTop-Calendar-Bridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "annotated-types==0.7.0",
    "certifi==2026.4.22",
    "charset-normalizer==3.4.7",
    "click==8.3.3",
    "colorama==0.4.6",
    "docopt==0.6.2",
    "greenlet==3.5.0",
    "idna==3.13",
    "jaraco-classes==3.4.0",
    "jaraco-context==6.1.2",
    "jaraco-functools==4.4.0",
    "keyring==25.7.0",
    "loguru>=0.7.3",
    "more-itertools==11.0.2",
    "openpyxl>=3.1.5",
    "packaging==26.2",
    "pandas>=3.0.6",
    "pip==24.3.1",
    "platformdirs==4.9.6",
    "playwright==1.59.0",
    "pydantic==2.13.3",
    "pydantic-core==2.46.3",
    "pydantic-settings==2.14.0",
    "pyee==13.0.1",
    "python-dotenv==1.2.2",
    "pywin32>=312",
    "pywin32-ctypes==0.2.3",
    "pyyaml==6.0.3",
    "requests==2.33.1",
    "requirements-parser==0.13.0",
    "tenacity==9.1.4",
    "tomli==2.4.1",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "urllib3==2.6.3",
    "win32-setctime==1.2.0",
    "yarg==0.1.10",
]